//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microservice.Smart.Services.GoogleMapInfo.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GoogleApi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoogleApi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microservice.Smart.Services.GoogleMapInfo.Tests.Resources.GoogleApi", typeof(GoogleApi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;destination_addresses&quot;: [
        ///    &quot;New York, NY, USA&quot;
        ///  ],
        ///  &quot;origin_addresses&quot;: [
        ///    &quot;Washington, DC, USA&quot;
        ///  ],
        ///  &quot;rows&quot;: [
        ///    {
        ///      &quot;elements&quot;: [
        ///        {
        ///          &quot;distance&quot;: {
        ///            &quot;text&quot;: &quot;228 mi&quot;,
        ///            &quot;value&quot;: 367654
        ///          },
        ///          &quot;duration&quot;: {
        ///            &quot;text&quot;: &quot;3 hours 55 mins&quot;,
        ///            &quot;value&quot;: 14078
        ///          },
        ///          &quot;status&quot;: &quot;OK&quot;
        ///        }
        ///      ]
        ///    }
        ///  ],
        ///  &quot;status&quot;: &quot;OK&quot;
        ///}.
        /// </summary>
        internal static string GoogleApi_Response_Success {
            get {
                return ResourceManager.GetString("GoogleApi_Response_Success", resourceCulture);
            }
        }
    }
}
